[experiment]

[metrics]

overall = ['visited_about_preferences', 'clicked_on_default_rally_call_to_action']
weekly = ['visited_about_preferences', 'clicked_on_default_rally_call_to_action']
daily = ['visited_about_preferences', 'clicked_on_default_rally_call_to_action']

[data_sources.preference_pane_interactions]
from_expression = """
    (
        SELECT
            DATE(submission_timestamp) AS submission_date,
            client_id,
            environment.experiments,
            p.key as pane
        FROM mozdata.telemetry.main
            CROSS JOIN UNNEST(payload.processes.parent.keyed_scalars.browser_ui_interaction_preferences_pane_More_From_Mozilla) AS p
        WHERE 
            SUBSTR(application.version, 0, 2) >= '97'
            AND normalized_channel = 'beta'
    )
"""
experiments_column_type = "native"


[metrics.visited_about_preferences]
friendly_name = "about:preferences Visits"
description = "Fraction of users that visited one of the sections of about:preferences"
data_source = "events"
select_expression = """
    COALESCE(MAX(
        CASE WHEN normalized_channel = 'beta'
          AND event_category = 'aboutpreferences'
          AND event_method = 'show'
          AND event_object IN ('initial',
                          'click','hash')
         THEN TRUE
         ELSE FALSE END), false)"""
bigger_is_better = true

[metrics.visited_about_preferences.statistics.binomial]



[metrics.clicked_on_default_rally_call_to_action]
friendly_name = "Clicked on Default Rally Call to Action"
description = "Fraction of users that clicked on the default Rally call to actions"
data_source = 'preference_pane_interactions'
select_expression = """COALESCE(MAX(
                CASE WHEN pane = 'default-mozillaRally'
                THEN true ELSE false END), false)"""
bigger_is_better = true

[metrics.clicked_on_default_rally_call_to_action.statistics.binomial]
